apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ve4es6ulz-nodejs 
  janus-idp.io/tekton: ve4es6ulz-nodejs
  backstage.io/kubernetes-id: ve4es6ulz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ve4es6ulz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  