apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ve4es6ulz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ve4es6ulz-nodejs 
  name: ve4es6ulz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ve4es6ulz-nodejs 
